set nocompatible
source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

set diffexpr=MyDiff()
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let eq = ''
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      let cmd = '""' . $VIMRUNTIME . '\diff"'
      let eq = '"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3 . eq
endfunction

"chen2liang4 config
colo murphy
set ic                      " ignore casesensitive
set sw=4                    " set TAB width
set ts=4
set expandtab               " change TAB to spaces, use Ctrl+V+Tab for inserting TAB
set softtabstop=4           " backspace to delete n whitespaces

set ai                      " Auto indent
set si                      " Smart indent

set guioptions+=b
set nu
set nobackup
set clipboard+=unnamed           " set clipboard to unnamed to access the system clipboard under windows
syntax on                       " turn syntax highlighting on by default

set encoding=utf-8
set fileencodings=utf-8,ucs-bom,shift-jis,latin1,big5,gb18030,gbk,gb2312,cp936
set fileencoding=utf-8
set termencoding=utf-8
set guifont=Consolas:h12

"解决中文菜单乱码
source $VIMRUNTIME/delmenu.vim  
source $VIMRUNTIME/menu.vim             

map    <C-Tab>    :tabn<CR>
map <C-w> <ESC>viw

"let b:javascript_fold=1
"let javascript_enable_domhtmlcss=1
